# Generated by Django 4.0.5 on 2022-08-16 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ideablog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='Description',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='IdeaName',
        ),
    ]
