# Generated by Django 4.0.5 on 2022-08-17 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ideablog', '0002_rename_content_post_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Description',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='post',
            name='IdeaName',
            field=models.CharField(max_length=20),
        ),
    ]
