# Generated by Django 4.0.5 on 2022-08-17 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ideablog', '0003_alter_post_description_alter_post_ideaname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Description',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='IdeaName',
            field=models.CharField(max_length=100),
        ),
    ]
